### ISSUE TITLE
Go to definition broken by aliases in Vim

### ISSUE THREAD

**Issue by rgrinberg** [the-lambda-church/merlin#426]
Easiest way to reproduce is to go to definition on the `String.blit` identifier. E.g.:

```ocaml
open Core.Std
let x = String.blit
```

This is the error:

```
Error detected while processing function merlin#Locate..provider#python#Call:
line   18:
NvimError('Cursor position outside buffer',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python2.7/site-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/local/lib/python2.7/site-packages/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
  File "/usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/provider/script_host.py", line 76, in python_execute
    exec(script, self.module.__dict__)
  File "<string>", line 1, in <module>
NvimError: Cursor position outside buffer
Error detected while processing function merlin#Locate:
line    4:
E171: Missing :endif
```

**Comment by trefis** [comment]
I... can't reproduce.
