### ISSUE TITLE
segfault from ppx_let

### ISSUE THREAD

**Issue by imeckler** [the-lambda-church/merlin#531]
The following ml file:
```ocaml
let foo = 0
```
with the following .merlin
```
S src
B _build/src
PKG core
PKG async
PKG ppx_let
```
results in the following error.
```
Error detected while processing function <SNR>51_BufWritePostHook..<SNR>51_UpdateErrors..<SNR>51_CacheErrors..30..29..SyntaxCheckers_ocaml_merlin_GetLocList..merlin#ErrorLocList:
line    9:
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/izzy/.opam/4.03.0/share/merlin/vim/autoload/merlin.py", line 449, in vim_loclist
    errors = command("errors")
  File "/Users/izzy/.opam/4.03.0/share/merlin/vim/autoload/merlin.py", line 170, in command
    return merlin_process().command(*cmd)
  File "/Users/izzy/.opam/4.03.0/share/merlin/vim/autoload/merlin.py", line 138, in command
    raise Error(content)
merlin.Error: {u'message': u"Error: Error while running external preprocessor\nCommand line: /Users/izzy/.opam/4.03.0/lib/ppx_let/./ppx '/var/folders/t6/g7qc8rbx2mn5jrzs4b83cpyc0000gn/T/camlppx275c85' '/var/folders/t6/g7qc8rbx2mn5jrzs4b83
cpyc0000gn/T/camlppx167c3c' 1>/dev/null 2>/dev/null\n", u'valid': True, u'type': u'type'}
Error detected while processing function <SNR>51_BufWritePostHook..<SNR>51_UpdateErrors..<SNR>51_CacheErrors:
Error detected while processing function <SNR>51_BufWritePostHook..<SNR>51_UpdateErrors..<SNR>51_CacheErrors:
line   35:
E170: Missing :endfor
Error detected while processing function <SNR>51_BufWritePostHook..<SNR>51_UpdateErrors:
line   15:
E171: Missing :endif
Press ENTER or type command to continuesh: line 1: 13963 Segmentation fault: 11  /Users/izzy/.opam/4.03.0/lib/ppx_let/./ppx '/var/folders/t6/g7qc8rbx2mn5jrzs4b83cpyc0000gn/T/camlppx2d60bd' '/var/folders/t6/g7qc8rbx2mn5jrzs4b83cpyc0000gn/T/camlppx661513' > /dev/null 2> /dev/null
```

The important part seems to be `ppx` segfaulting, but I included the whole error in case something else is useful. Strangely, changing the ml to
```ocaml
let foo = ()
```
gets rid of the segfault.

**Comment by let-def** [comment]
Which version of merlin?

**Comment by imeckler** [comment]
"The Merlin toolkit version 2.3.1, for Ocaml 4.03.0"

**Comment by let-def** [comment]
OCaml 4.03.0 is only supported in the git version.
The 2.3.1 targeted a binary incompatible alpha of 4.03.

**Comment by imeckler** [comment]
I see, thanks.
