### ISSUE TITLE
Issue when starting merling for first time

### ISSUE THREAD

**Issue by micronova** [the-lambda-church/merlin#556]
I installed merlin
added these lines to my .vimrc

```
filetype plugin on
let g:opamshare = substitute(system('opam con    fig var share'),'\n$','','''')
execute "set rtp+=" . g:opamshare . "/merlin/    vim"
let g:syntastic_ocaml_checkers = ['merlin']
```

and when I try to open an empty file I got this:

```
"start.ml" [Nouveau fichier]
Erreur détectée en traitant function ocpindex#init :
ligne    2 :
ocpindex: ocp-index not found
Erreur détectée en traitant function merlin#Register[117]..merlin#LoadProject :
ligne    2 :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/micronova/.opam/4.01.0/share/merlin/vim/autoload/merlin.py", line 844, in setup_merlin

    acquire_buffer(force=True)
  File "/home/micronova/.opam/4.01.0/share/merlin/vim/autoload/merlin.py", line 328, in acquire_buff
er
    command_checkout(name=vim.eval("expand('%:p')"))
  File "/home/micronova/.opam/4.01.0/share/merlin/vim/autoload/merlin.py", line 228, in command_chec
kout
    r = command("checkout",kind,name)
  File "/home/micronova/.opam/4.01.0/share/merlin/vim/autoload/merlin.py", line 170, in command
    return merlin_process().command(*cmd)
  File "/home/micronova/.opam/4.01.0/share/merlin/vim/autoload/merlin.py", line 136, in command
    raise Failure(content)
merlin.Failure: u'invalid arguments'
```

**Comment by let-def** [comment]
Sorry for the delay... The first error is related to ocp-index.

The second error suggests that you might be using an incorrect version of Merlin.
Please note that we are no longer supporting OCaml 4.01.
