### ISSUE TITLE
Error of merlin#Register[117] on Neovim

### ISSUE THREAD

**Issue by liweijian** [the-lambda-church/merlin#573]
I just `brew update` and `brew upgrade` my OS X 10.11.6, then I started neovim to edit some OCaml file, there's error:

```shell
"t.ml" 2L, 20C
Error detected while processing function merlin#Register[117]..merlin#LoadProject[2]..provider#python3#Call:
line   18:
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/Users/liweijian/.opam/4.03.0/share/merlin/vim/autoload/merlin.py", line 736, in setup_merlin
    failures = command("project","get")

  File "/Users/liweijian/.opam/4.03.0/share/merlin/vim/autoload/merlin.py", line 201, in command
    return merlin_process().command(context(cmd))

  File "/Users/liweijian/.opam/4.03.0/share/merlin/vim/autoload/merlin.py", line 175, in merlin_process
    instance = vim.eval("merlin#SelectBinary()")

  File "/Users/liweijian/Library/Python/3.5/lib/python/site-packages/neovim/plugin/script_host.py", line 187, in eval
    obj = self.request("vim_eval", expr)

  File "/Users/liweijian/Library/Python/3.5/lib/python/site-packages/neovim/api/nvim.py", line 129, in request
    res = self._session.request(name, *args, **kwargs)

  File "/Users/liweijian/Library/Python/3.5/lib/python/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)

neovim.api.nvim.NvimError: b'Vim(let):E716:
Error detected while processing function merlin#Register[117]..merlin#LoadProject:
line    2:
E171: Missing :endif
Error detected while processing function <SNR>9_LoadFTPlugin:
line   17:
E170: Missing :endfor
```

After searching for answer, I found @rgrinberg [mentioned before](http://www.gitterforum.com/discussion/neovim-neovim?page=1703), but I couldn't find the solution in that page.

Any idea to fix it?

**Comment by liweijian** [comment]
Append my `init.vim` here:

```vim

autocmd FileType ocaml setlocal et sta sw=2 sts=2
let g:opamshare = substitute(system('opam config var share'),'\n$','','''')
autocmd FileType ocaml execute "set rtp+=" . g:opamshare . "/ocp-indent/vim"
autocmd FileType ocaml execute "set rtp+=" . g:opamshare . "/merlin/vim"

let g:syntastic_ocaml_checkers = ['merlin']
autocmd FileType ocaml nnoremap <localleader>ml :MerlinLocate<CR>
autocmd FileType ocaml nnoremap <localleader>mr :MerlinRename <space>
autocmd FileType ocaml nnoremap <localleader>mo :MerlinOccurrences<CR>
autocmd FileType ocaml nnoremap <localleader>ol :MerlinOutline<CR>
autocmd FileType ocaml nnoremap <silent><esc> :nohlsearch<return>:MerlinClearEnclosing<return><esc>

function! s:ocaml_format()
    let now_line = line('.')
    exec ':%! ocp-indent'
    exec ':' . now_line
endfunction

augroup ocaml_format
    autocmd!
    autocmd BufWrite,FileWritePre,FileAppendPre *.mli\= call s:ocaml_format()
augroup END

let g:python3_host_prog = '/usr/local/bin/python3'
```

**Comment by liweijian** [comment]
It seems that's because some error from my `init.vim`, I just chaned

> autocmd FileType ocaml execute "set rtp+=" . g:opamshare . "/merlin/vim"

to

> execute "set rtp+=" . g:opamshare . "/merlin/vim"

And it works right now.
