### ISSUE TITLE
"Not a compiled interface" error with OCaml 4.04

### ISSUE THREAD

**Issue by mmottl** [the-lambda-church/merlin#600]
Since upgrading to OCaml 4.04, I've been running into the following issue whenever I try to save a file in Vim:

```
Error detected while processing function <SNR>80_BufWritePostHook[4]..<SNR>80_UpdateErrors[15]..<SNR>80_CacheErrors[37]..501[1]..500[24]..SyntaxCheckers_ocaml_merlin_GetLocList[1]..merlin#ErrorLocList:
line    8:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/mmottl/.opam/4.04.0/share/merlin/vim/autoload/merlin.py", line 399, in vim_loclist
    errors = query("errors")
  File "/Users/mmottl/.opam/4.04.0/share/merlin/vim/autoload/merlin.py", line 211, in query
    return command(*cmd)
  File "/Users/mmottl/.opam/4.04.0/share/merlin/vim/autoload/merlin.py", line 201, in command
    return merlin_process().command(context(cmd))
  File "/Users/mmottl/.opam/4.04.0/share/merlin/vim/autoload/merlin.py", line 168, in command
    raise Error(value)
merlin.Error: {u'message': u'Error: /Users/mmottl/.opam/4.04.0/lib/ocaml/pervasives.cmi\nis not a compiled interface for this version of OCaml.\nIt seems to be for a newer version of OCaml.', u'valid': True, u'type': u'type', u'sub': []}
Error detected while processing function <SNR>80_BufWritePostHook[4]..<SNR>80_UpdateErrors[15]..<SNR>80_CacheErrors:
line   37:
E170: Missing :endfor
Error detected while processing function <SNR>80_BufWritePostHook[4]..<SNR>80_UpdateErrors:
line   15:
E171: Missing :endif
```

OCaml 4.03 was working just fine.

**Comment by let-def** [comment]
4.04 support is not yet released, and opam constraints were too permissive. I am working on it.

You can try the beta version now with `opam pin add merlin --dev-repo`.

**Comment by mmottl** [comment]
Thanks for the fast reply.  Choosing opam constraints is like being caught between a rock and a hard place.  Be too permissive and people will complain about broken packages when upgrading compilers.  Be too restrictive and people will complain about missing packages that might actually be supported just fine.

**Comment by kkirstein** [comment]
I had the same issue and just upgraded to merlin 2.5.2. It now works with ocaml 4.04. My "toolchain" is: Windows, cygwin & mingw64, merlin & atom.

**Comment by let-def** [comment]
Thanks.
